### ISSUE TITLE
Featuring just in Docusaurus

### ISSUE THREAD

**Issue by joybhallaa** [microsoft/just#116]
Hello, we would like to feature this project to the Docusarus [users](https://docusaurus.io/en/users).

If you are okay with it, can you provide us with a logo? 
More information about this issue can be found here [here](https://github.com/facebook/Docusaurus/issues/1437).

**Comment by joybhallaa** [comment]
Hey guys, will appreciate if you can see this issue and revert back

**Comment by anikethsaha** [comment]
is this still on !. 
I think @Ayushsahnios can help us with a logo. 
 
cc @kenotron
