### ISSUE TITLE
tscTask() does not support mutually exclusive `build` option

### ISSUE THREAD

**Issue by ScottHysom** [microsoft/just#123]
For better or worse, TypeScript chose to make the `--build` CLI parameter mutually exclusive from all other parameters, including the `project` parameter. Further, TypeScript requires the use of the `--build` parameter in order to respect the `composite: true` and/or `references` options in the tsconfig.json. 

This conflicts with Just's current implementation of `tscTask()`, which always sets the `project` if it can successfully find the tsconfig.json.

**Proposal**: If `build` is `true` in the `options` argument to `tscTask()`, then skip setting the `options.project` value itself and instead provide the path to the discovered tsConfigFile as documented in https://www.typescriptlang.org/docs/handbook/project-references.html and party on.

**Comment by kenotron** [comment]
Good catch!

**Comment by kenotron** [comment]
Congrats on making the bug #123... It's being addressed in #128

**Comment by kenotron** [comment]
This has been released on just-scripts 0.21!
