### ISSUE TITLE
Sample has missing import

### ISSUE THREAD

**Issue by stanlemon** [microsoft/just#140]
Hello!

Over on:
![](https://microsoft.github.io/just/img/sample-2x.png)
(Visible on https://microsoft.github.io/just/)

You'll notice that `parallel()` is not imported on that first line.

**Comment by kenotron** [comment]
Awesome! PR's are welcome! But I'll fix this soon - wishing that this was HTML rather than an image...

**Comment by stanlemon** [comment]
@kenotron I contemplated submitting a PR to do that but I wasn’t sure if there would be a preferred highlighter or way to do so? If you’ve got desired deps I’m happy to submit something.

**Comment by jadczakd** [comment]
I believe it was submitted as output of a tool called Carbon - https://carbon.now.sh/

corrected oputput - sorry I didn't have time to look for the proper colour scheme :) 
![carbon](https://user-images.githubusercontent.com/20739064/60163318-a148d080-97fb-11e9-814c-c1b2c4eb9b72.png)

[editable-link](https://carbon.now.sh/?bg=rgba(171%252C%2520184%252C%2520195%252C%25201)&t=paraiso-dark&wt=none&l=javascript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=48px&ph=32px&ln=false&fm=Hack&fs=14px&lh=133%2525&si=false&es=2x&wm=false&code=const%2520%257B%2520task%252C%2520option%252C%2520logger%252C%2520argv%252C%2520parallel%2520%257D%2520%253D%2520require(%27just-task%27)%253B%250A%250Aoption(%27name%27%252C%2520%257B%2520default%253A%2520%27world%27%257D)%253B%250A%250Atask(%27say-hello%27%252C%2520function()%2520%257B%250A%2520%2520logger.info(%27hello%2520%27%2520%252B%2520argv().name)%253B%250A%257D)%253B%250A%250Atask(%27say-hi%27%252C%2520function()%2520%257B%250A%2520%2520logger.info(%27hi%2520%27%2520%252B%2520argv().name)%253B%250A%257D)%253B%250A%250Atask(%27say-it-all%27%252C%2520parallel(%27say-hello%27%252C%2520%27say-hi%27)))

**Comment by stanlemon** [comment]
Submitted, thank you! ❤️
