### ISSUE TITLE
just-scripts depends upon a version of just-task that doesn't exist

### ISSUE THREAD

**Issue by boneskull** [microsoft/just#146]
...but I'm not sure why `just-task` isn't a peer dep, but it would seem that you'd want to `npm i just-task -D` and then `npm i just-scripts -D` if you wanted the helpers.

**Comment by beary** [comment]
I meet this problem too
```bash
$ npm i just-task -D
$ npm i just-scripts -D

npm ERR! code ETARGET
npm ERR! notarget No matching version found for just-task@>=0.11.0 <1.0.0      
npm ERR! notarget In most cases you or one of your dependencies are requesting 
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'just-scripts'
npm ERR! notarget
```

The latest version of `just-task` is 0.10.0 but `just-scripts` needs [at least 0.11.0](https://github.com/microsoft/just/blob/6ad6fc58f8cbea86e196bd2818cadc16efc599d5/packages/just-scripts/package.json#L23) 😥

**Comment by adamelliotfields** [comment]
For now, if you're just looking to try out Just, you can use version `0.20.0` of `just-scripts`.

Appears this issue has existed in both the `0.23.1` and `0.24.0` releases.

```
npm i -D just-scripts@0.20.0 just-task@0.10.0
```

**Comment by kenotron** [comment]
wow... some weirdness in publishing probably!
