### ISSUE TITLE
Command line arguments example is unclear

### ISSUE THREAD

**Issue by jadczakd** [microsoft/just#151]
The provided example is unclear with the output it's supposed to create.
```
const { task, logger, option, argv } = require('just-task');

option('name');

task('blimey', 'An exclamation of surprise.', function() {
  logger.info(`blimey! ${argv().name}`);
});
```
using the suggested command results in the same output for me
command
```
just --help
just blimey --help
```
output
```
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

Shouldn't it be printing something about the name argument? At least denoting it's there and can be used?

I've tried changing the options definition to the following:
```
option('name', {
  describe: 'description',
  type: 'string'
});
```
and 
```
option('name', {
  describe: 'description',
  type: 'string'
}).usage("$0 -name string").help();
```
with no luck - I would expect the arguments to be somehow listed when the --help flag is passed to the task.

**Comment by newyork-anthonyng** [comment]
Running `just` by itself gives me this output:

```
just <cmd> [options]

Tasks:

  just blimey  An exclamation of surprise.

Options:
  --version  Show version number                                       [boolean]
  --config   path to a just-task.js file (includes the file name)
  --name
  --help     Show help                                                 [boolean]

No default tasks are defined.
[12:28:13 PM] x Error previously detected. See above for error messages.
```

Should we update the `docs` to reflect this? Or should we do code changes to have `just --help` have the same output as `just`.

Also, what do we expect `just blimey --help` to return? I believe it should return a description for `blimey` as well as the `options` that it accepts. However, with the current API, there's no way to associate an `option` with a `task`.

@kenotron thoughts?

**Comment by anikethsaha** [comment]
As far as the optimal behaviour is concerned it should print the helping message when passed with `--help` flag. I guess its an issue !....

**Comment by jadczakd** [comment]
just on it's own indeed prints everything.
just with --help however doesn't neither does just taskname --help

I will take more time to look at this on Sunday at the earliest, but seems like a good issue to get familiar with yargs and just : )

**Comment by jadczakd** [comment]
Seem to me like a good first issue to get familiar with yargs and just in general.

I will have more time for it next week most likely so feel free to tweak unless opposed by the author ;)

**Comment by anikethsaha** [comment]
I guess the options are a wrapper for yargs. If it so then just check if anything missing in the yargs implementation. Cause yargs should take care of command `--help` flag

**Comment by kenotron** [comment]
Show help is not very much help at the moment for the options it seems. I mainly did as much as possible to list 

> Running `just` by itself gives me this output:
> 
> ```
> just <cmd> [options]
> 
> Tasks:
> 
>   just blimey  An exclamation of surprise.
> 
> Options:
>   --version  Show version number                                       [boolean]
>   --config   path to a just-task.js file (includes the file name)
>   --name
>   --help     Show help                                                 [boolean]
> 
> No default tasks are defined.
> [12:28:13 PM] x Error previously detected. See above for error messages.
> ```
> 
> Should we update the `docs` to reflect this? Or should we do code changes to have `just --help` have the same output as `just`.
> 
> Also, what do we expect `just blimey --help` to return? I believe it should return a description for `blimey` as well as the `options` that it accepts. However, with the current API, there's no way to associate an `option` with a `task`.
> 
> @kenotron Ken Chau FTE thoughts?

The issue here is that options and tasks are defined all in one. That's actually how it would work elsewhere. In a `just.config.js` that has multiple tasks defined and multiple options, you could actually run any of the tasks with any of the options. This means that options aren't really tied to a task. All options are essentially global.

I really think the help message should include all options and all tasks like when you run `just` by itself. This is a bug - probably because I'm using yargs in a way that's not how it's directly designed to do. I'm considering switching to yargs-parser and handle command and help inside just-task itself.
