### ISSUE TITLE
No example on command line commands

### ISSUE THREAD

**Issue by nayots** [microsoft/just#158]
There is no clear example on how to create a task that executes a command line command.

For example how would you execute a task that starts with "ng build" and then runs some other command line task.

**Comment by kenotron** [comment]
Do you mean how to run this thing like

`ng build`

Which would translate to `build -> tsc, webpack` etc? I think that is the point of this document page:
https://microsoft.github.io/just/docs/doc-start.html

I actually am not familiar with how `ng` command line works but if you stick with the doc there, you would see that there's not a need to call `ng`. `just` would take over the build command... does that make sense?

**Comment by stwel** [comment]
Not really what i mean.
What i mean is to integrate command line commands execution in the tasks, something like what https://www.npmjs.com/package/gulp-shell is doing ?

**Comment by beary** [comment]
Maybe this?
```typescript
const { task } = require('just-task')
const { exec } = require('just-scripts-utils')

task('build', () => {
  return exec('echo "hello world!"', {
    stderr: process.stderr,
    stdout: process.stdout
  })
})
```
```bash
$ npx just build

[5:39:55 PM] ■ started 'build'
hello world!
[5:39:55 PM] ■ finished 'build' in 0.01s
```

This should be placed in the document.
