### ISSUE TITLE
Passing custom config does not work as expected

### ISSUE THREAD

**Issue by matthewrobb** [microsoft/just#159]
When passing `--config ./some-root-relative-path` it appears to skip calling the resolver function.

The issue seems to be with this line https://github.com/microsoft/just/blob/master/packages/just-task/src/JustTaskRegistry.ts#L16

What it ultimately ends up doing is trying to require relative to `node_modules/just-task/lib`

**Comment by anikethsaha** [comment]
Thanks for pointing out. It seems the bug may be in https://github.com/microsoft/just/blob/faf567519184dca2a22dc04d1bd95aec695a8488/packages/just-task/src/JustTaskRegistry.ts#L20 
I guess there the current working directory is not being added. can you just try to replace that line with 
```js
 const configModule = require(require("path").join(process.cwd(),configFile))
```
and check once again

Not sure whether this is the fix but you can give it a shot

**Comment by matthewrobb** [comment]
@anikethsaha Actually it's really simple what's not happening. The following would fix the issue:
Before:
```js
let configFile = [yargs.argv.config, './just.config.js', './just-task.js'].reduce((value, entry) => value || resolve(entry));
```
After:
```js
let configFile = [resolve(yargs.argv.config), './just.config.js', './just-task.js'].reduce((value, entry) => value || resolve(entry));
```

**Comment by anikethsaha** [comment]
Yup, that will work too. Feel free to submit a PR!

**Comment by anikethsaha** [comment]
@matthewrobb can you raise a PR with this fix 👍

**Comment by anikethsaha** [comment]
ping @matthewrobb
