### ISSUE TITLE
npx just gives command not found: just

### ISSUE THREAD

**Issue by justin-calleja** [microsoft/just#161]
Expected to use npx as in getting started guide. Instead got:

```
npx just
npx: installed 1 in 1.55s
command not found: just
```

Current environment at time of issue:
```
➜  workspace node -v
v8.12.0
➜  workspace npm -v
6.4.1
```

Also: using `just-task` doesn't work either:

```
npx just-task sayhello
npx: installed 104 in 10.198s
[13:42:22] x Invalid configuration file: /blah/blah/just-task.js
[13:42:22] x Error: Cannot find module 'just-task'
```

**Comment by anikethsaha** [comment]
you need to install `just-task` as a dependency first using `npm i -D just-task` 
and then you create your task file and then using the command `npm just` , it will run all your task mentioned in the `just-task.js`

You can also use the preferable project structure using `npm init just` and then select the project type!

**Comment by anikethsaha** [comment]
> [13:42:22] x Invalid configuration file: /blah/blah/just-task.js
[13:42:22] x Error: Cannot find module 'just-task'

this issue is mentioned already in here https://github.com/microsoft/just/issues/159 and its fix is coming soon !

**Comment by justin-calleja** [comment]
@anikethsaha ok thanks. I thought I could use `npx` to run `just` without installing in `node_modules`.

Confirmed use of `npx` works after local install:

```
# mkdir tmp-project && cd !$ && npm init -y
➜  tmp-project npm i -D just-task

➜  tmp-project npx just sayhello
[7:07:17 PM] ■ started 'sayhello'
[7:07:17 PM] ■ world
[7:07:17 PM] ■ finished 'sayhello' in 0.01s
```

**Comment by aashish-g03** [comment]
Hi @manideepk90, 
I noticed that the issue isn't marked as high priority. If it's not an urgent requirement, could you please assign it to me? I'm still familiarizing myself with open source contributions and would love to take this on. In case I encounter any difficulties, I’ll be sure to let you know so we can reassign if needed.
