### ISSUE TITLE
[Proposal] : Migrating to yeoman-generator for create-just package

### ISSUE THREAD

**Issue by anikethsaha** [microsoft/just#163]
### Proposal
**package :** **`create-just`**

Currently, the generating method in `create-just` package is quite rough and as mentioned by @kenotron it is immature too. There are few issues here and there about copying the generating the packages. What I am suggesting is to migrate the whole create-just to `yeoman-generator` which is a proven library used by many packages. 
The migration a first stage we can just wrap the yeoman over the existing with few refactor to support the package.

**Packages Required :** 
1. [`yeoman-environment`](https://github.com/yeoman/environment)
2. [`types`](https://www.npmjs.com/package/@types/yeoman-generator)
3. [`yeoman-generator`](https://github.com/yeoman/generator)

**Refactor requires:** 
- In `https://github.com/microsoft/just/blob/master/packages/create-just/src/index.ts`
need to use the package - Need to set up the environment for the `yeoman` using `yeoman-environment` and pass the `yargs` parsed arguments generator class
- commands are gonna be same as they are now, need to change the `handler` method
- In a new folder `https://github.com/microsoft/just/blob/master/packages/create-just/src/generator` 👇 
- Based on the arguments(or not if not passed), prompt the existing question and extract the logic of finding the project in a separate method and use it to find the package.
- Copy the `template` from them
- Install the dependency
- ALL SET

All log messages and utils can be used as they are used now

**Comment by anikethsaha** [comment]
@kenotron thoughts ?

**Comment by kenotron** [comment]
I don't mind using good tech for generation. One thing I strived to achieve and probably possible here is to have things rolled up / webpacked for the `create-just` package so that generation from `npx init just` would take less than a couple of seconds to boot. Probably possible with yoeman... but are there lighter weight, well-tested, well used template generators out there as well?

**Comment by anikethsaha** [comment]
I guess one more is there https://github.com/jondot/hygen ,  but never used this. 
yeoman is quite smooth, I have used it for one of my [project](https://github.com/buildtip/create-web-app), it added/creates a whole MERN stack project and Its quite fast till now. 
It adds few (2-3) more dependencies to the project. And maybe we cant overwrite their logs with custom logs during file creation 
I will give yeoman a shot and will share the repo with you if you think it's fine, then we can go with the migration!

**Comment by kenotron** [comment]
@anikethsaha after doing a bit of research, I think what I have created is more closely aligned with "plop". Though hygen looks really great too - I also like the ejs choice.

**Comment by anikethsaha** [comment]
I didn't use `plop`, although their demo in docs looks great. I guess it is more like file creation than whole project creation. Yeah, we can give it a try.

**Comment by kenotron** [comment]
So I've integrated this! Have a try with it - see if it works like you want. I've updated the just-stack-* packages to use it so you can see what it's like to generate whole repos.
