### ISSUE TITLE
Create webpackCliTask to use webpack-cli

### ISSUE THREAD

**Issue by kenotron** [microsoft/just#168]
Currently, `webpackTask` has to take on lots of functionality that is already codified inside `webpack-cli` package, we should treat webpack's cli as the API surface for this task to simplify the task.

**Comment by anikethsaha** [comment]
as far as the current version of `webpack-cli` there are quite a few `generators` (`yeoman-generators`) which we can use order to manage the `webpack.config.js` file. We can even use them as `node` API.  

Also I guess the APIs may change ! , 

There are few packages (`add, update..etc`) which are gonna remove from in next release which is on this Aug

**Comment by kenotron** [comment]
This has been added in the latest version!
