### ISSUE TITLE
Comparison to other task runners

### ISSUE THREAD

**Issue by gaui** [microsoft/just#190]
Would you be so kind to add comparison to other task runners like Gulp and Grunt.

**Comment by ShawnTalbert** [comment]
Indeed, why create this when Gulp already exists?  Curious as to the motivation? Just NIH syndrome?

**Comment by kenotron** [comment]
Nope, not a NIH syndrome. I had a blurp of why not gulp before - but actually if you dig a teeny bit, you'd see that we're using gulp's task runner under the hood. We're just not doing vinylfs and focus on productivity of task function writers.

**Comment by anikethsaha** [comment]
I think it can be tested or benchmarked against tools like [`taskr`](https://github.com/lukeed/taskr). 
though this is more like a light weight thing

**Comment by kenotron** [comment]
Would love to do a comparison. But I'm thinking that's more of a blog post idea?

**Comment by kenotron** [comment]
Keeping this open in case I get some time to write a post about it :)
