### ISSUE TITLE
'just' not recognized!

### ISSUE THREAD

**Issue by mike-barnett** [microsoft/just#191]
I tried to follow the directions I found in issue #161 but it just changed the error message. Whereas before "npm start" (where "start" is defined in my package.json as "just start") resulted in an error saying that the command 'just' was not recognized, now I get an error from just complaining that it is an invalid configuration file. Yet in a sibling directory with an identical package.json (except for the "name" node) and an identical just-task.js file, 'just' runs perfectly. This is completely blocking me so any help would be greatly appreciated!

**Comment by anikethsaha** [comment]
I think the problem must be in your installing the dependencies. 
It would be helpful if you can show your `package.json`

**Comment by mike-barnett** [comment]
Thanks! Yes, it turned out that I had somehow corrupted my package-lock.json. So the dependencies in my package.json were fine: once I re-generated the package-lock file it works fine.
