### ISSUE TITLE
Doc screenshots are squished on mobile

### ISSUE THREAD

**Issue by moltar** [microsoft/just#193]
![GitHawk Upload by moltar](https://i.imgur.com/h7jZ2hc.jpg)

Thank you

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by neilbryson** [comment]
Works fine on my phone on Chrome and Firefox Focus, and also on the simulated view on Chrome and Firefox desktop.

**Comment by moltar** [comment]
My screenshot is from iPhone SE Safari

**Comment by kenotron** [comment]
Good first bug for anyone out in the community to fix!
