### ISSUE TITLE
TypeScript monorepo with Rush.js, with at least one package, leveraging Jest, Plop, Just, Just Scripts.

### ISSUE THREAD

**Issue by renoirb** [microsoft/just#210]
In documentation, about [stacks-monorepo](https://microsoft.github.io/just/docs/stacks-monorepo), it says

> Just uses the Rush library to manage monorepos.

When I follow the steps, it doesn't.

## Intention

I am willing to make a PR to support this use-case (without breaking the use of Lerna or Beachball). This is to know if there are plans to support such use-case.

## Reproduction repo

**Use-Case**: Have a TypeScript monorepo (ideally with Rush, because it is now my new favourite over Lerna), with at least one item, process to run tests, plop files, and run tests.

**See**: https://github.com/renoirb/experiments-201908-just-plop-typescript-monorepo-rushjs

Steps:

```terminal
npm init just
cd monorepo-created
npm run gen
# ...
```

But I've had to change things a bit after that so I could get to to work. (not visible in Git history)

**Comment by kenotron** [comment]
That's right, I hadn't updated the docs. We've switched to lerna. Kind of strapped for time at the moment fixing bugs in another repo. Feel free to submit a PR if you find these inconsistencies.

**Comment by renoirb** [comment]
Is the switch to Lerna and Yarn workspace monorepo a choice based on some technical superiority. Or it went in that tangent and you guys plan to support it back?

The code looks like there can be more than only one possible monorepo stack.

If that's the case, I can make a PR to add a scaffold to plop a rush monorepo.  I guess the difference would be to make a "npx just-task rush-monorepo" instead of creating a top level package.json file. Then docs would be easy to adjust to mention both possibilities.

I'm saying this because I have been using  Lerna for more than a year and I've tried RushJs for a werk. Rush was more helpful for telling build errors and package dependencies. Whoch is very useful for a team. Not all members in a team are NPM packaging ninjas after all..

Back to my question. If there are plans to support back, but just need to be done again because it is in a backlog, tell me. I might help.

**Comment by kenotron** [comment]
Rush is actually technically superior in that it provides a lot out of the box. Lerna is missing the following:

1. automated semver via change files (Lerna uses commit messages which is meh)
2. incremental builds

That said, the change file automated versioning has been filled by another piece of software called `beachball`. Incremental builds is another matter - just-task has support for this and could be used to help speed things up.

The issue I found with Rush centers around the fact that it assumes a lot and it doesn't actually have as big of install base amongst the most popular monorepos out there. We actually have found both to be good solutions, but the purpose of the `just-stack-monorepo` is to get new users up and running with very familiar tools. We could use a `just-stack-rush-monorepo` as well to make sure those who want to use Rush has a good starting point as well.

**Comment by renoirb** [comment]
Thanks for the feedback, I could work some more on a Just+Rush integration, it's here https://github.com/renoirb/experiments-201908-rush-typescript-just-bili-monorepo

**Comment by kenotron** [comment]
Oh yeah, the stacks so far are for a typescript (the npm package) centric repo. I like the idea of offering both babel and rollup support for just-scripts as well. Though I kind of wonder if there's a point where we should build out an ecosystem vs all inside just-scripts.
