### ISSUE TITLE
Clarify story for modifying a task from a preset

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/just#22]
Suppose I want to mostly use the `webapp` preset as-is, but I want to modify the `'build'` task (maybe to build scss or codepen examples before ts). How should I do that?

Related question: how do I know the names of the existing tasks provided by a preset?

**Comment by kenotron** [comment]
We need documentation I believe on this.

**Comment by ecraig12345** [comment]
Very much still an issue. before/after solves some cases but not if the task you want to modify is in the middle of a chain. And there's still no way to know the available task names from a preset.

**Comment by ecraig12345** [comment]
No longer relevant since presets are gone
