### ISSUE TITLE
Add ability to mix in config when creating a task (webpack, jest, others?)

### ISSUE THREAD

**Issue by ecraig12345** [microsoft/just#24]
For certain task factories (especially webpack and jest, maybe others), it should be possible to pass in config options which are mixed in with the defaults. Some possible ways to do this:
1. If relevant config file exists in the project dir, just loads the file and mixes its options in with defaults
2. Add a utility in just for merging config with default, then call the utility in each project's relevant config file

We should also consider whether the default config for any tasks could be improved.

Possible inspiration: Fabric's [webpack-resources.js](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/scripts/webpack/webpack-resources.js) and [jest-resources.js](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/scripts/jest/jest-resources.js)

**Comment by kenotron** [comment]
So we've added this stuff for webpack, but not jest. I think we already added the options arg for those tasks. Hopefully that's good enough? Please re-open if that didn't get addressed as I think this bug might have been created before those options were added to the tasks.
