### ISSUE TITLE
Name collision with existing project 

### ISSUE THREAD

**Issue by corbinu** [microsoft/just#254]
I am currently not able to use this in any node projects as its name collides with an existing command runner: https://github.com/casey/just

**Comment by kenotron** [comment]
Usually, you use this library as a npm script like `react-scripts` from `create-react-app`:

```json
{
  "scripts": {
    "build": "just-scripts build"
  }
}
```

Does that work for you? It would really help to see if there's a sample repo that you run into here. The documentation certainly should fix this up a bit so that that's the default recommendation.

**Comment by corbinu** [comment]
Ya I guess I just have to use locally.
