### ISSUE TITLE
Confusing "no webpack config configuration found, skipping" error message on yarn start

### ISSUE THREAD

**Issue by jkovzels** [microsoft/just#289]
I keep getting `▲ no webpack.serve.config.js configuration found, skipping` `webpack-dev-server` is not installed and it is confusing because config is there but `devServerCmd` is null at [webpackTask.ts:100](https://github.com/microsoft/just/blob/6a680840bf838bcbfb175b37fff0d61bb6530b75/packages/just-scripts/src/tasks/webpackTask.ts#L100)

And frankly I have no clue why it soddenly stopped to resolve `webpack-dev-server` because is was not in dependencies nor before nor after.

Fixed by adding webpack stack

**Comment by ecraig12345** [comment]
This seems to be fixed in the template now too. Root cause would be similar to #290 probably.
