### ISSUE TITLE
[Question] The state of Just vs @rushstack/heft

### ISSUE THREAD

**Issue by ScottAwesome** [microsoft/just#455]
My question centers around what the state of this project is going forward considering Heft is now live and is very similar. As both are Microsoft projects I’d be curious to know if there will be consolidation here? Should we migrate to heft if using Just?

https://rushstack.io/pages/heft/overview/

**Comment by ecraig12345** [comment]
As I'm guessing you've put together by now 😬 Just is kind of in maintenance mode. Other projects are still welcome to use it if it fits their needs, but Heft could be a better choice if you want something with more active development and support.
