### ISSUE TITLE
[docs] Guide button leads to 404

### ISSUE THREAD

**Issue by techeverri** [microsoft/just#487]
## Description

Clicking the "Guide" button in the navigation menu of the [documentation page (GitHub Pages)](https://microsoft.github.io/just/) leads to 404

### Step 1: Click the "Guide" button

<img width="1008" alt="Pasted_Image_2020-11-03__01_04" src="https://user-images.githubusercontent.com/3720424/97932696-f93d0300-1d70-11eb-8c15-951b16936d05.png">

### Result: It navigates to 404

🔗 https://microsoft.github.io/just/guide

<img width="1008" alt="Pasted_Image_2020-11-03__01_05" src="https://user-images.githubusercontent.com/3720424/97932731-0ce86980-1d71-11eb-8fe4-e4b528702daf.png">

**Comment by ecraig12345** [comment]
Fixed in 344042c
