### ISSUE TITLE
bug: just-scripts 1.x is missing ../lib/cli thus cannot be run

### ISSUE THREAD

**Issue by Hotell** [microsoft/just#502]
**version:** just-scripts@1.3.0

**error:**  
![image](https://user-images.githubusercontent.com/1223799/104614716-cb394080-5688-11eb-850d-84c9d16215f8.png)

**Comment by dbcottam** [comment]
I have this same issue.  I tried decreasing the version number to 1.2.6 and the issue remains but adds another required stack.

**Comment by ecraig12345** [comment]
Cleaning up old issues--not sure what happened, but it's fixed now, in [v1](https://unpkg.com/browse/just-scripts@1.8.2/lib/cli.js) and [v2](https://unpkg.com/browse/just-scripts@2.1.2/lib/cli.js).
