### ISSUE TITLE
Add Just to Docusaurus Featured Projects List

### ISSUE THREAD

**Issue by co16353sidak** [microsoft/just#86]
Hey Everyone,
Docusaurus would like to add this project onto it's display of featured Docusaurus.
basically these are open source projects using docusaurus for setting up their documentation.
(Which is why Just will look perfect up there.)

What I would require would be a logo for the same, which can be linked to the featured projects list on Docusaurus.
So I would need permissions and files for the same, looking forward for some replies to this.

cc and links:
facebook/Docusaurus#1080
https://docusaurus.io/en/users

P.S: a sample PR as to how this process occurred for another user
facebook/Docusaurus#1275
😃🎉🚀

**Comment by kenotron** [comment]
Great idea! Looks like I need to come up with a good logo to get on there huh :)

**Comment by co16353sidak** [comment]
Waiting up on you then 😄 @kenotron

**Comment by kenotron** [comment]
Sorry, been busy adding features and such... not a logo artist :( So I might need some help from folks in the community to help.

**Comment by anikethsaha** [comment]
https://github.com/microsoft/just/issues/116#issuecomment-506759396
