### ISSUE TITLE
Getting started steps don't work

### ISSUE THREAD

**Issue by akrantz** [microsoft/just#90]
I just tried these steps: https://microsoft.github.io/just/docs/doc-start.

1. I created a new npm package:
```
mkdir play
cd play
npm init -y
```

2. I installed just-task:
```
npm install -D just-task
```

3. I used VS Code to create a new file "just-task.js" containing:
```
const { task, option, logger, argv } = require('just-task');

option('name', { default: 'world' });

task('sayhello', function() {
  logger.info(argv().name);
});
```

4. Then I tried running the sayhello task:
```
npx just sayhello
```

RESULT: 
```
[5:34:29 AM] x Cannot find config file "null". Please create a file called "just-task.js" in the root of the project next to "package.json".
```

**Comment by kenotron** [comment]
Hmmm I can't repro this, @akrantz... Can you try to see if there's a old global copy of `just-task` sitting around your HD? I just tried this in a clean env (inside a docker) in Linux, and then on Windows was okay as well as Mac... 

Would you mind doing a little investigation here?

**Comment by akrantz** [comment]
@kenotron Well, I just tried this steps and it worked now.
